export const USER_GET_DATA_SUCCESS = 'USER_GET_ALL_DATA';
export const USER_GET_DATA_REQUEST = 'USER_GET_DATA_REQUEST';
export const USER_GET_DATA_FAIL = 'USER_GET_DATA_FAIL';


export const AUTH_GET_DATA_SUCCESS = 'AUTH_GET_ALL_DATA';
export const AUTH_GET_DATA_REQUEST = 'AUTH_GET_DATA_REQUEST';
export const AUTH_GET_DATA_FAIL = 'AUTH_GET_DATA_FAIL';


export const SINGLE_GET_DATA_SUCCESS = 'SINGLE_GET_ALL_DATA';
export const SINGLE_GET_DATA_REQUEST = 'SINGLE_GET_DATA_REQUEST';
export const SINGLE_GET_DATA_FAIL = 'SINGLE_GET_DATA_FAIL';